### ISSUE TITLE
Tthe :inst field of Instruction was renamed to :stmt

### ISSUE THREAD

**Issue by mschauer** [dfdx/Umlaut.jl#58]
See https://github.com/JuliaLang/julia/pull/50868

Relevant for
https://github.com/dfdx/Umlaut.jl/blob/828988cb8b1775ac73310bf3765ffabaf12d9888/src/trace.jl#L28

**Comment by dfdx** [comment]
Thanks! It has been fixed in #55 and released in Umlaut v0.7.0. Note that this version drops support for Julia < 1.10, so if you are going to use earlier version of Julia, you probably want to fix Umlaut to v0.6.3.
